# Dockerfile.frontend
FROM node:lts AS build
WORKDIR /app/webui
COPY webui/ ./
RUN yarn install --no-progress --network-timeout 600000
# usa lo script che hai: 'yarn build' o 'yarn run build-prod'
RUN yarn build

FROM nginxinc/nginx-unprivileged:stable
COPY --from=build /app/webui/dist /usr/share/nginx/html
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
