# Dockerfile.frontend

# Build stage
FROM node:lts-alpine AS builder
WORKDIR /app
COPY webui/package.json webui/yarn.lock* ./
RUN yarn install
COPY webui/ .
RUN yarn run build

# Production stage
FROM nginx:stable-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
USER 1000
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
