# Dockerfile.backend

FROM golang:1.17-alpine AS builder
WORKDIR /app
COPY . .
RUN go build -o /app/webapi ./cmd/webapi/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/webapi .
COPY --from=builder /app/service/api/pictureslol ./service/api/pictureslol
EXPOSE 8082
CMD ["./webapi"]