services:
  backend:
    image: wasa-backend:final
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - PORT=3000
      - GIN_MODE=release
    ports:
      - "3000:3000"

  frontend:
    image: wasa-frontend:final
    build:
      context: .
      dockerfile: Dockerfile.frontend
    # Fallback (se la tua Docker Desktop esegue non-root): sblocca user root
    # user: "0:0"
    environment:
      - API_BASE=/api
    ports:
      - "8080:80"
    depends_on:
      - backend
