# docker-compose.yml (solo per uso tuo)
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: wasa-backend:local
    environment:
      - GIN_MODE=release
    ports:
      - "3000:3000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: wasa-frontend:local
    depends_on: [backend]
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf:ro
